### ISSUE TITLE
07 strings: Avoid in-place methods?

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/programming-for-lawyers#12]
The exercise "Inverting Names" introduces `reverse()`, which modifies the list in-place rather than returning a new list:

```python
def invert_name(name):
    """
    Convert a name from regular to inverted form
    >>> invert_name('John Doe')
    'Doe, John'
    """
    name_parts = name.split(" ")
    name_parts.reverse()
    reversed_name = ", ".join(name_parts)
    return reversed_name

print(invert_name("John Doe"))
```

Since functions is still a quite fresh concept, it's possible that it's better to stick to functions that return something at this point. We could use `reversed(list)` instead of `list.reverse()`:

```python
def invert_name(name):
    """
    Convert a name from regular to inverted form
    >>> invert_name('John Doe')
    'Doe, John'
    """
    name_parts = name.split(" ")
    reversed_name_parts = reversed(name_parts)
    reversed_name = ", ".join(reversed_name_parts)
    return reversed_name

print(invert_name("John Doe"))
```

Only downside is that methods that return generators can potentially be confusing in it's own right.

**Comment by ewinge** [comment]
fixed in 26e7b0b8e51475a7e164d3c85c250327700890c5
